#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.y;
  float offset1 = one_pixel * 1.4998785523439397;
  float offset2 = one_pixel * 3.4997166221358595;
  float offset3 = one_pixel * 5.499554691927779;
  float offset4 = one_pixel * 7.499392761719699;
  float offset5 = one_pixel * 9.499230831511618;
  float offset6 = one_pixel * 11.499068901303538;
  float offset7 = one_pixel * 13.498906971095458;
  float offset8 = one_pixel * 15.498745040887378;
  float offset9 = one_pixel * 17.4985831106793;
  float offset10 = one_pixel * 19.498421180471215;
  float offset11 = one_pixel * 21.498259250263136;
  float offset12 = one_pixel * 23.498097320055056;
  float offset13 = one_pixel * 25.497935389846976;
  float offset14 = one_pixel * 27.497773459638896;
  float offset15 = one_pixel * 29.497611529430817;
  float offset16 = one_pixel * 31.497449599222733;
  float offset17 = one_pixel * 33.49728766901465;
  float offset18 = one_pixel * 35.497125738806574;
  float offset19 = one_pixel * 37.496963808598494;
  float offset20 = one_pixel * 39.496801878390414;
  float offset21 = one_pixel * 41.496639948182334;
  float offset22 = one_pixel * 43.496478017974255;
  float offset23 = one_pixel * 45.496316087766175;
  float offset24 = one_pixel * 47.496154157558095;
  float offset25 = one_pixel * 49.495992227350015;
  float offset26 = one_pixel * 51.49583029714193;
  float offset27 = one_pixel * 53.49566836693385;
  float offset28 = one_pixel * 55.49550643672577;
  float offset29 = one_pixel * 57.49534450651769;
  float offset30 = one_pixel * 59.49518257630961;
  float offset31 = one_pixel * 61.49502064610153;
  float offset32 = one_pixel * 63.49485871589345;
  float offset33 = one_pixel * 65.49469678568536;
  float offset34 = one_pixel * 67.49453485547728;
  float offset35 = one_pixel * 69.4943729252692;
  float offset36 = one_pixel * 71.49421099506112;
  float offset37 = one_pixel * 73.49404906485304;
  float offset38 = one_pixel * 75.49388713464496;
  float offset39 = one_pixel * 77.49372520443688;
  float offset40 = one_pixel * 79.4935632742288;
  float offset41 = one_pixel * 81.49340134402073;
  float offset42 = one_pixel * 83.49323941381265;
  float offset43 = one_pixel * 85.49307748360457;
  float offset44 = one_pixel * 87.49291555339649;
  float offset45 = one_pixel * 89.4927536231884;
  float offset46 = one_pixel * 91.49259169298033;
  float offset47 = one_pixel * 93.49242976277225;
  float offset48 = one_pixel * 95.49226783256417;
  float offset49 = one_pixel * 97.49210590235609;
  float offset50 = one_pixel * 99.49194397214801;
  float offset51 = one_pixel * 101.49178204193993;
  float offset52 = one_pixel * 103.49162011173185;
  float offset53 = one_pixel * 105.49145818152377;
  float offset54 = one_pixel * 107.49129625131569;
  float offset55 = one_pixel * 109.49113432110761;
  float offset56 = one_pixel * 111.49097239089953;
  float offset57 = one_pixel * 113.49081046069143;
  float offset58 = one_pixel * 115.49064853048336;
  float offset59 = one_pixel * 117.49048660027528;
  float offset60 = one_pixel * 119.4903246700672;
  float offset61 = one_pixel * 121.49016273985912;
  float offset62 = one_pixel * 123.49000080965104;
  float offset63 = one_pixel * 125.48983887944296;
  float offset64 = one_pixel * 127.48967694923488;
  float offset65 = one_pixel * 129.4895150190268;
  float offset66 = one_pixel * 131.48935308881872;
  float offset67 = one_pixel * 133.48919115861065;
  float offset68 = one_pixel * 135.48902922840256;

  f_color = (
    0.0007448226164990696 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset68)) +
    0.0008126262334682635 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset67)) +
    0.0008854539922812344 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset66)) +
    0.0009635590832751963 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset65)) +
    0.0010471958056510354 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset64)) +
    0.0011366182915922838 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset63)) +
    0.0012320791199603648 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset62)) +
    0.001333827821210457 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset61)) +
    0.0014421092763402166 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset60)) +
    0.001557162013920771 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset59)) +
    0.0016792164105567167 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset58)) +
    0.0018084928014686222 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset57)) +
    0.0019451995092754804 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset56)) +
    0.0020895308004619355 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset55)) +
    0.0022416647804307656 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset54)) +
    0.002401761239448563 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset53)) +
    0.0025699594631742417 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset52)) +
    0.002746376022797261 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset51)) +
    0.0029311025610859864 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset50)) +
    0.0031242035918363936 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset49)) +
    0.0033257143312972015 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset48)) +
    0.0035356385811091797 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset47)) +
    0.003753946683113856 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset46)) +
    0.003980573567040728 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset45)) +
    0.004215416912553877 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset44)) +
    0.004458335447411311 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset43)) +
    0.004709147403547732 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset42)) +
    0.004967629152719956 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset41)) +
    0.005233514042942297 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset40)) +
    0.005506491456277817 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset39)) +
    0.005786206107634136 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset38)) +
    0.006072257603036291 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset37)) +
    0.006364200274413938 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset36)) +
    0.006661543306249493 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset35)) +
    0.006963751167494604 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset34)) +
    0.00727024435998538 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset33)) +
    0.007580400492186357 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset32)) +
    0.007893555684487318 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset31)) +
    0.008209006309487366 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset30)) +
    0.008526011067751936 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset29)) +
    0.008843793396449076 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset28)) +
    0.009161544205092175 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset27)) +
    0.009478424929371286 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset26)) +
    0.009793570890779988 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset25)) +
    0.010106094946477118 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset24)) +
    0.010415091410601658 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset23)) +
    0.010719640225124335 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset22)) +
    0.011018811355311037 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset21)) +
    0.011311669382030709 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset20)) +
    0.011597278260502702 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset19)) +
    0.011874706212682795 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset18)) +
    0.012143030718368565 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset17)) +
    0.012401343568295876 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset16)) +
    0.012648755941028359 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset15)) +
    0.012884403464336464 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset14)) +
    0.013107451221043514 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset13)) +
    0.013317098658999995 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset12)) +
    0.013512584364946166 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset11)) +
    0.013693190662543814 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset10)) +
    0.013858247995801919 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset9)) +
    0.014007139060484392 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset8)) +
    0.014139302647860955 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset7)) +
    0.01425423716733003 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset6)) +
    0.014351503816984482 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset5)) +
    0.014430729374081975 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset4)) +
    0.01449160858059114 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset3)) +
    0.014533906102478088 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset2)) +
    0.01455745804513633 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset1)) +
    0.007281676019578852 * texture(sampler2D(t_input, s_input), coords) +
    0.01455745804513633 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset1)) +
    0.014533906102478088 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset2)) +
    0.01449160858059114 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset3)) +
    0.014430729374081975 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset4)) +
    0.014351503816984482 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset5)) +
    0.01425423716733003 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset6)) +
    0.014139302647860955 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset7)) +
    0.014007139060484392 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset8)) +
    0.013858247995801919 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset9)) +
    0.013693190662543814 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset10)) +
    0.013512584364946166 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset11)) +
    0.013317098658999995 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset12)) +
    0.013107451221043514 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset13)) +
    0.012884403464336464 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset14)) +
    0.012648755941028359 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset15)) +
    0.012401343568295876 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset16)) +
    0.012143030718368565 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset17)) +
    0.011874706212682795 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset18)) +
    0.011597278260502702 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset19)) +
    0.011311669382030709 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset20)) +
    0.011018811355311037 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset21)) +
    0.010719640225124335 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset22)) +
    0.010415091410601658 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset23)) +
    0.010106094946477118 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset24)) +
    0.009793570890779988 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset25)) +
    0.009478424929371286 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset26)) +
    0.009161544205092175 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset27)) +
    0.008843793396449076 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset28)) +
    0.008526011067751936 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset29)) +
    0.008209006309487366 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset30)) +
    0.007893555684487318 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset31)) +
    0.007580400492186357 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset32)) +
    0.00727024435998538 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset33)) +
    0.006963751167494604 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset34)) +
    0.006661543306249493 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset35)) +
    0.006364200274413938 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset36)) +
    0.006072257603036291 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset37)) +
    0.005786206107634136 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset38)) +
    0.005506491456277817 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset39)) +
    0.005233514042942297 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset40)) +
    0.004967629152719956 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset41)) +
    0.004709147403547732 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset42)) +
    0.004458335447411311 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset43)) +
    0.004215416912553877 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset44)) +
    0.003980573567040728 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset45)) +
    0.003753946683113856 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset46)) +
    0.0035356385811091797 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset47)) +
    0.0033257143312972015 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset48)) +
    0.0031242035918363936 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset49)) +
    0.0029311025610859864 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset50)) +
    0.002746376022797261 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset51)) +
    0.0025699594631742417 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset52)) +
    0.002401761239448563 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset53)) +
    0.0022416647804307656 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset54)) +
    0.0020895308004619355 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset55)) +
    0.0019451995092754804 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset56)) +
    0.0018084928014686222 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset57)) +
    0.0016792164105567167 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset58)) +
    0.001557162013920771 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset59)) +
    0.0014421092763402166 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset60)) +
    0.001333827821210457 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset61)) +
    0.0012320791199603648 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset62)) +
    0.0011366182915922838 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset63)) +
    0.0010471958056510354 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset64)) +
    0.0009635590832751963 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset65)) +
    0.0008854539922812344 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset66)) +
    0.0008126262334682635 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset67)) +
    0.0007448226164990696 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset68))
  );
}
