#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.y;
  float offset1 = one_pixel * 1.4913294797687862;
  float offset2 = one_pixel * 3.479768786127168;
  float offset3 = one_pixel * 5.468208092485549;
  float offset4 = one_pixel * 7.456647398843931;
  float offset5 = one_pixel * 9.445086705202312;
  float offset6 = one_pixel * 11.433526011560694;
  float offset7 = one_pixel * 13.421965317919074;
  float offset8 = one_pixel * 15.410404624277456;

  f_color = (
    0.007632918268355388 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset8)) +
    0.014960868341057308 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset7)) +
    0.026686954338102226 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset6)) +
    0.04335033970232395 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset5)) +
    0.06416019118552328 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset4)) +
    0.08655685051602538 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset3)) +
    0.10647281112550169 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset2)) +
    0.11944638895171829 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset1)) +
    0.061465355142785 * texture(sampler2D(t_input, s_input), coords) +
    0.11944638895171829 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset1)) +
    0.10647281112550169 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset2)) +
    0.08655685051602538 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset3)) +
    0.06416019118552328 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset4)) +
    0.04335033970232395 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset5)) +
    0.026686954338102226 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset6)) +
    0.014960868341057308 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset7)) +
    0.007632918268355388 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset8))
  );
}
