#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.y;
  float offset1 = one_pixel * 1.4944237918215613;
  float offset2 = one_pixel * 3.486988847583643;
  float offset3 = one_pixel * 5.479553903345725;
  float offset4 = one_pixel * 7.4721189591078065;
  float offset5 = one_pixel * 9.464684014869889;
  float offset6 = one_pixel * 11.45724907063197;
  float offset7 = one_pixel * 13.449814126394052;
  float offset8 = one_pixel * 15.442379182156134;
  float offset9 = one_pixel * 17.434944237918216;
  float offset10 = one_pixel * 19.4275092936803;

  f_color = (
    0.005826928287698983 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset10)) +
    0.010115980276655131 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset9)) +
    0.016534822625679287 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset8)) +
    0.02545132821514684 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset7)) +
    0.036899846504647116 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset6)) +
    0.05039804841957287 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset5)) +
    0.06485418154329738 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset4)) +
    0.0786404083611858 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset3)) +
    0.08986155882023933 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset2)) +
    0.09677162400634795 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset1)) +
    0.04929054587905866 * texture(sampler2D(t_input, s_input), coords) +
    0.09677162400634795 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset1)) +
    0.08986155882023933 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset2)) +
    0.0786404083611858 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset3)) +
    0.06485418154329738 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset4)) +
    0.05039804841957287 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset5)) +
    0.036899846504647116 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset6)) +
    0.02545132821514684 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset7)) +
    0.016534822625679287 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset8)) +
    0.010115980276655131 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset9)) +
    0.005826928287698983 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset10))
  );
}
