#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_scaling;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.y;
  float offset1 = one_pixel * 1.4978102189781022;
  float offset2 = one_pixel * 3.4948905109489052;
  float offset3 = one_pixel * 5.491970802919708;
  float offset4 = one_pixel * 7.489051094890511;
  float offset5 = one_pixel * 9.486131386861313;
  float offset6 = one_pixel * 11.483211678832117;
  float offset7 = one_pixel * 13.48029197080292;
  float offset8 = one_pixel * 15.477372262773722;
  float offset9 = one_pixel * 17.474452554744527;
  float offset10 = one_pixel * 19.471532846715327;
  float offset11 = one_pixel * 21.46861313868613;
  float offset12 = one_pixel * 23.465693430656934;
  float offset13 = one_pixel * 25.462773722627738;
  float offset14 = one_pixel * 27.45985401459854;
  float offset15 = one_pixel * 29.456934306569345;
  float offset16 = one_pixel * 31.454014598540144;

  gl_FragColor = (
    0.003407814043148431 * texture2D(u_texture, vec2(coords.x, coords.y - offset16)) +
    0.0048680764586640085 * texture2D(u_texture, vec2(coords.x, coords.y - offset15)) +
    0.006792568680751563 * texture2D(u_texture, vec2(coords.x, coords.y - offset14)) +
    0.00925797031089537 * texture2D(u_texture, vec2(coords.x, coords.y - offset13)) +
    0.012325707678360885 * texture2D(u_texture, vec2(coords.x, coords.y - offset12)) +
    0.016029899617915018 * texture2D(u_texture, vec2(coords.x, coords.y - offset11)) +
    0.020364812571528057 * texture2D(u_texture, vec2(coords.x, coords.y - offset10)) +
    0.02527364137200788 * texture2D(u_texture, vec2(coords.x, coords.y - offset9)) +
    0.030640751683066906 * texture2D(u_texture, vec2(coords.x, coords.y - offset8)) +
    0.036289494306527996 * texture2D(u_texture, vec2(coords.x, coords.y - offset7)) +
    0.04198724059744583 * texture2D(u_texture, vec2(coords.x, coords.y - offset6)) +
    0.04745838814300468 * texture2D(u_texture, vec2(coords.x, coords.y - offset5)) +
    0.052404850941500714 * texture2D(u_texture, vec2(coords.x, coords.y - offset4)) +
    0.056532186506502685 * texture2D(u_texture, vec2(coords.x, coords.y - offset3)) +
    0.05957829950410395 * texture2D(u_texture, vec2(coords.x, coords.y - offset2)) +
    0.061340879867214836 * texture2D(u_texture, vec2(coords.x, coords.y - offset1)) +
    0.030894835434722382 * texture2D(u_texture, coords) +
    0.061340879867214836 * texture2D(u_texture, vec2(coords.x, coords.y + offset1)) +
    0.05957829950410395 * texture2D(u_texture, vec2(coords.x, coords.y + offset2)) +
    0.056532186506502685 * texture2D(u_texture, vec2(coords.x, coords.y + offset3)) +
    0.052404850941500714 * texture2D(u_texture, vec2(coords.x, coords.y + offset4)) +
    0.04745838814300468 * texture2D(u_texture, vec2(coords.x, coords.y + offset5)) +
    0.04198724059744583 * texture2D(u_texture, vec2(coords.x, coords.y + offset6)) +
    0.036289494306527996 * texture2D(u_texture, vec2(coords.x, coords.y + offset7)) +
    0.030640751683066906 * texture2D(u_texture, vec2(coords.x, coords.y + offset8)) +
    0.02527364137200788 * texture2D(u_texture, vec2(coords.x, coords.y + offset9)) +
    0.020364812571528057 * texture2D(u_texture, vec2(coords.x, coords.y + offset10)) +
    0.016029899617915018 * texture2D(u_texture, vec2(coords.x, coords.y + offset11)) +
    0.012325707678360885 * texture2D(u_texture, vec2(coords.x, coords.y + offset12)) +
    0.00925797031089537 * texture2D(u_texture, vec2(coords.x, coords.y + offset13)) +
    0.006792568680751563 * texture2D(u_texture, vec2(coords.x, coords.y + offset14)) +
    0.0048680764586640085 * texture2D(u_texture, vec2(coords.x, coords.y + offset15)) +
    0.003407814043148431 * texture2D(u_texture, vec2(coords.x, coords.y + offset16))
  );
}
