#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.y;
  float offset1 = one_pixel * 1.4985994397759104;
  float offset2 = one_pixel * 3.496732026143791;
  float offset3 = one_pixel * 5.494864612511671;
  float offset4 = one_pixel * 7.492997198879552;
  float offset5 = one_pixel * 9.491129785247432;
  float offset6 = one_pixel * 11.489262371615313;
  float offset7 = one_pixel * 13.487394957983193;
  float offset8 = one_pixel * 15.485527544351074;
  float offset9 = one_pixel * 17.483660130718953;
  float offset10 = one_pixel * 19.481792717086833;
  float offset11 = one_pixel * 21.479925303454714;
  float offset12 = one_pixel * 23.478057889822594;
  float offset13 = one_pixel * 25.476190476190474;
  float offset14 = one_pixel * 27.474323062558355;
  float offset15 = one_pixel * 29.472455648926235;
  float offset16 = one_pixel * 31.470588235294116;
  float offset17 = one_pixel * 33.468720821662;
  float offset18 = one_pixel * 35.46685340802988;
  float offset19 = one_pixel * 37.46498599439776;
  float offset20 = one_pixel * 39.46311858076564;

  f_color = (
    0.002681774635923218 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset20)) +
    0.0035761545925612234 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset19)) +
    0.004697820138835657 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset18)) +
    0.006079472610901071 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset17)) +
    0.007750469058909791 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset16)) +
    0.009733870900964458 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset15)) +
    0.012043187894288366 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset14)) +
    0.014679058934782559 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset13)) +
    0.017626181640438818 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset12)) +
    0.020850849999806423 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset11)) +
    0.02429947105494111 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset10)) +
    0.027898397964432248 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset9)) +
    0.031555333366795356 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset8)) +
    0.03516242628311063 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset7)) +
    0.038601018318152755 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset6)) +
    0.04174780855671243 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset5)) +
    0.04448202475739643 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset4)) +
    0.046693036980598186 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset3)) +
    0.04828775265675472 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset2)) +
    0.049197107359624515 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y - offset1)) +
    0.02471356458814008 * texture(sampler2D(t_input, s_input), coords) +
    0.049197107359624515 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset1)) +
    0.04828775265675472 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset2)) +
    0.046693036980598186 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset3)) +
    0.04448202475739643 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset4)) +
    0.04174780855671243 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset5)) +
    0.038601018318152755 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset6)) +
    0.03516242628311063 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset7)) +
    0.031555333366795356 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset8)) +
    0.027898397964432248 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset9)) +
    0.02429947105494111 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset10)) +
    0.020850849999806423 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset11)) +
    0.017626181640438818 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset12)) +
    0.014679058934782559 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset13)) +
    0.012043187894288366 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset14)) +
    0.009733870900964458 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset15)) +
    0.007750469058909791 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset16)) +
    0.006079472610901071 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset17)) +
    0.004697820138835657 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset18)) +
    0.0035761545925612234 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset19)) +
    0.002681774635923218 * texture(sampler2D(t_input, s_input), vec2(coords.x, coords.y + offset20))
  );
}
