#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_dimensions;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy / u_dimensions.xy;

  float one_pixel = u_dimensions.w;
  float offset1 = one_pixel * 1.4992840095465394;
  float offset2 = one_pixel * 3.498329355608592;
  float offset3 = one_pixel * 5.497374701670644;
  float offset4 = one_pixel * 7.4964200477326965;
  float offset5 = one_pixel * 9.495465393794749;
  float offset6 = one_pixel * 11.494510739856802;
  float offset7 = one_pixel * 13.493556085918854;
  float offset8 = one_pixel * 15.492601431980907;
  float offset9 = one_pixel * 17.49164677804296;
  float offset10 = one_pixel * 19.490692124105014;
  float offset11 = one_pixel * 21.489737470167064;
  float offset12 = one_pixel * 23.48878281622912;
  float offset13 = one_pixel * 25.48782816229117;
  float offset14 = one_pixel * 27.486873508353224;
  float offset15 = one_pixel * 29.485918854415274;
  float offset16 = one_pixel * 31.48496420047733;
  float offset17 = one_pixel * 33.48400954653938;
  float offset18 = one_pixel * 35.48305489260143;
  float offset19 = one_pixel * 37.482100238663485;
  float offset20 = one_pixel * 39.48114558472554;
  float offset21 = one_pixel * 41.480190930787586;
  float offset22 = one_pixel * 43.47923627684964;
  float offset23 = one_pixel * 45.478281622911695;
  float offset24 = one_pixel * 47.47732696897375;
  float offset25 = one_pixel * 49.476372315035796;
  float offset26 = one_pixel * 51.47541766109785;
  float offset27 = one_pixel * 53.474463007159905;
  float offset28 = one_pixel * 55.47350835322196;

  gl_FragColor = (
    0.0018671250238015897 * texture2D(u_texture, vec2(coords.x, coords.y - offset28)) +
    0.0022992959460498897 * texture2D(u_texture, vec2(coords.x, coords.y - offset27)) +
    0.002809910314888722 * texture2D(u_texture, vec2(coords.x, coords.y - offset26)) +
    0.0034077426636591646 * texture2D(u_texture, vec2(coords.x, coords.y - offset25)) +
    0.004101271168597975 * texture2D(u_texture, vec2(coords.x, coords.y - offset24)) +
    0.004898330981392433 * texture2D(u_texture, vec2(coords.x, coords.y - offset23)) +
    0.005805722605914156 * texture2D(u_texture, vec2(coords.x, coords.y - offset22)) +
    0.00682878575880741 * texture2D(u_texture, vec2(coords.x, coords.y - offset21)) +
    0.00797095321655091 * texture2D(u_texture, vec2(coords.x, coords.y - offset20)) +
    0.009233303039947847 * texture2D(u_texture, vec2(coords.x, coords.y - offset19)) +
    0.010614130960036692 * texture2D(u_texture, vec2(coords.x, coords.y - offset18)) +
    0.012108567268270623 * texture2D(u_texture, vec2(coords.x, coords.y - offset17)) +
    0.013708263948606133 * texture2D(u_texture, vec2(coords.x, coords.y - offset16)) +
    0.01540117773005141 * texture2D(u_texture, vec2(coords.x, coords.y - offset15)) +
    0.017171473007779194 * texture2D(u_texture, vec2(coords.x, coords.y - offset14)) +
    0.018999565064306573 * texture2D(u_texture, vec2(coords.x, coords.y - offset13)) +
    0.020862318732252933 * texture2D(u_texture, vec2(coords.x, coords.y - offset12)) +
    0.022733410733228633 * texture2D(u_texture, vec2(coords.x, coords.y - offset11)) +
    0.024583855707986754 * texture2D(u_texture, vec2(coords.x, coords.y - offset10)) +
    0.026382686864511413 * texture2D(u_texture, vec2(coords.x, coords.y - offset9)) +
    0.02809777277215407 * texture2D(u_texture, vec2(coords.x, coords.y - offset8)) +
    0.029696742758899605 * texture2D(u_texture, vec2(coords.x, coords.y - offset7)) +
    0.031147985293887702 * texture2D(u_texture, vec2(coords.x, coords.y - offset6)) +
    0.03242167730293983 * texture2D(u_texture, vec2(coords.x, coords.y - offset5)) +
    0.03349079813441457 * texture2D(u_texture, vec2(coords.x, coords.y - offset4)) +
    0.03433208029478979 * texture2D(u_texture, vec2(coords.x, coords.y - offset3)) +
    0.0349268503570925 * texture2D(u_texture, vec2(coords.x, coords.y - offset2)) +
    0.03526171764989381 * texture2D(u_texture, vec2(coords.x, coords.y - offset1)) +
    0.01767296939857534 * texture2D(u_texture, coords) +
    0.03526171764989381 * texture2D(u_texture, vec2(coords.x, coords.y + offset1)) +
    0.0349268503570925 * texture2D(u_texture, vec2(coords.x, coords.y + offset2)) +
    0.03433208029478979 * texture2D(u_texture, vec2(coords.x, coords.y + offset3)) +
    0.03349079813441457 * texture2D(u_texture, vec2(coords.x, coords.y + offset4)) +
    0.03242167730293983 * texture2D(u_texture, vec2(coords.x, coords.y + offset5)) +
    0.031147985293887702 * texture2D(u_texture, vec2(coords.x, coords.y + offset6)) +
    0.029696742758899605 * texture2D(u_texture, vec2(coords.x, coords.y + offset7)) +
    0.02809777277215407 * texture2D(u_texture, vec2(coords.x, coords.y + offset8)) +
    0.026382686864511413 * texture2D(u_texture, vec2(coords.x, coords.y + offset9)) +
    0.024583855707986754 * texture2D(u_texture, vec2(coords.x, coords.y + offset10)) +
    0.022733410733228633 * texture2D(u_texture, vec2(coords.x, coords.y + offset11)) +
    0.020862318732252933 * texture2D(u_texture, vec2(coords.x, coords.y + offset12)) +
    0.018999565064306573 * texture2D(u_texture, vec2(coords.x, coords.y + offset13)) +
    0.017171473007779194 * texture2D(u_texture, vec2(coords.x, coords.y + offset14)) +
    0.01540117773005141 * texture2D(u_texture, vec2(coords.x, coords.y + offset15)) +
    0.013708263948606133 * texture2D(u_texture, vec2(coords.x, coords.y + offset16)) +
    0.012108567268270623 * texture2D(u_texture, vec2(coords.x, coords.y + offset17)) +
    0.010614130960036692 * texture2D(u_texture, vec2(coords.x, coords.y + offset18)) +
    0.009233303039947847 * texture2D(u_texture, vec2(coords.x, coords.y + offset19)) +
    0.00797095321655091 * texture2D(u_texture, vec2(coords.x, coords.y + offset20)) +
    0.00682878575880741 * texture2D(u_texture, vec2(coords.x, coords.y + offset21)) +
    0.005805722605914156 * texture2D(u_texture, vec2(coords.x, coords.y + offset22)) +
    0.004898330981392433 * texture2D(u_texture, vec2(coords.x, coords.y + offset23)) +
    0.004101271168597975 * texture2D(u_texture, vec2(coords.x, coords.y + offset24)) +
    0.0034077426636591646 * texture2D(u_texture, vec2(coords.x, coords.y + offset25)) +
    0.002809910314888722 * texture2D(u_texture, vec2(coords.x, coords.y + offset26)) +
    0.0022992959460498897 * texture2D(u_texture, vec2(coords.x, coords.y + offset27)) +
    0.0018671250238015897 * texture2D(u_texture, vec2(coords.x, coords.y + offset28))
  );
}
