#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_scaling;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.y;
  float offset1 = one_pixel * 1.49941611521993;
  float offset2 = one_pixel * 3.4986376021798367;
  float offset3 = one_pixel * 5.497859089139743;
  float offset4 = one_pixel * 7.497080576099649;
  float offset5 = one_pixel * 9.496302063059556;
  float offset6 = one_pixel * 11.495523550019463;
  float offset7 = one_pixel * 13.494745036979369;
  float offset8 = one_pixel * 15.493966523939276;
  float offset9 = one_pixel * 17.493188010899182;
  float offset10 = one_pixel * 19.49240949785909;
  float offset11 = one_pixel * 21.491630984818997;
  float offset12 = one_pixel * 23.4908524717789;
  float offset13 = one_pixel * 25.490073958738808;
  float offset14 = one_pixel * 27.489295445698716;
  float offset15 = one_pixel * 29.488516932658623;
  float offset16 = one_pixel * 31.48773841961853;
  float offset17 = one_pixel * 33.486959906578434;
  float offset18 = one_pixel * 35.486181393538345;
  float offset19 = one_pixel * 37.48540288049825;
  float offset20 = one_pixel * 39.48462436745815;
  float offset21 = one_pixel * 41.483845854418064;
  float offset22 = one_pixel * 43.48306734137797;
  float offset23 = one_pixel * 45.48228882833787;
  float offset24 = one_pixel * 47.48151031529778;
  float offset25 = one_pixel * 49.48073180225769;
  float offset26 = one_pixel * 51.4799532892176;
  float offset27 = one_pixel * 53.4791747761775;
  float offset28 = one_pixel * 55.478396263137405;
  float offset29 = one_pixel * 57.477617750097316;
  float offset30 = one_pixel * 59.47683923705722;
  float offset31 = one_pixel * 61.476060724017124;

  gl_FragColor = (
    0.0016796466329463044 * texture2D(u_texture, vec2(coords.x, coords.y - offset31)) +
    0.002027999116237829 * texture2D(u_texture, vec2(coords.x, coords.y - offset30)) +
    0.0024333692176280773 * texture2D(u_texture, vec2(coords.x, coords.y - offset29)) +
    0.0029016100972999656 * texture2D(u_texture, vec2(coords.x, coords.y - offset28)) +
    0.0034384385311574546 * texture2D(u_texture, vec2(coords.x, coords.y - offset27)) +
    0.00404925382541444 * texture2D(u_texture, vec2(coords.x, coords.y - offset26)) +
    0.00473893342663415 * texture2D(u_texture, vec2(coords.x, coords.y - offset25)) +
    0.005511609198954715 * texture2D(u_texture, vec2(coords.x, coords.y - offset24)) +
    0.0063704299652471465 * texture2D(u_texture, vec2(coords.x, coords.y - offset23)) +
    0.0073173175207766235 * texture2D(u_texture, vec2(coords.x, coords.y - offset22)) +
    0.008352724827403008 * texture2D(u_texture, vec2(coords.x, coords.y - offset21)) +
    0.009475406375021447 * texture2D(u_texture, vec2(coords.x, coords.y - offset20)) +
    0.010682211643494349 * texture2D(u_texture, vec2(coords.x, coords.y - offset19)) +
    0.011967913106226058 * texture2D(u_texture, vec2(coords.x, coords.y - offset18)) +
    0.013325080192478378 * texture2D(u_texture, vec2(coords.x, coords.y - offset17)) +
    0.014744009998103672 * texture2D(u_texture, vec2(coords.x, coords.y - offset16)) +
    0.016212724262197352 * texture2D(u_texture, vec2(coords.x, coords.y - offset15)) +
    0.017717040205760082 * texture2D(u_texture, vec2(coords.x, coords.y - offset14)) +
    0.01924072029507983 * texture2D(u_texture, vec2(coords.x, coords.y - offset13)) +
    0.02076570292838887 * texture2D(u_texture, vec2(coords.x, coords.y - offset12)) +
    0.02227241257354246 * texture2D(u_texture, vec2(coords.x, coords.y - offset11)) +
    0.02374014416962627 * texture2D(u_texture, vec2(coords.x, coords.y - offset10)) +
    0.02514751283981269 * texture2D(u_texture, vec2(coords.x, coords.y - offset9)) +
    0.026472956359477513 * texture2D(u_texture, vec2(coords.x, coords.y - offset8)) +
    0.02769527460196242 * texture2D(u_texture, vec2(coords.x, coords.y - offset7)) +
    0.028794187555304007 * texture2D(u_texture, vec2(coords.x, coords.y - offset6)) +
    0.02975089165378017 * texture2D(u_texture, vec2(coords.x, coords.y - offset5)) +
    0.030548593246925385 * texture2D(u_texture, vec2(coords.x, coords.y - offset4)) +
    0.03117299813360437 * texture2D(u_texture, vec2(coords.x, coords.y - offset3)) +
    0.03161273725759824 * texture2D(u_texture, vec2(coords.x, coords.y - offset2)) +
    0.031859710866498095 * texture2D(u_texture, vec2(coords.x, coords.y - offset1)) +
    0.015960878750837258 * texture2D(u_texture, coords) +
    0.031859710866498095 * texture2D(u_texture, vec2(coords.x, coords.y + offset1)) +
    0.03161273725759824 * texture2D(u_texture, vec2(coords.x, coords.y + offset2)) +
    0.03117299813360437 * texture2D(u_texture, vec2(coords.x, coords.y + offset3)) +
    0.030548593246925385 * texture2D(u_texture, vec2(coords.x, coords.y + offset4)) +
    0.02975089165378017 * texture2D(u_texture, vec2(coords.x, coords.y + offset5)) +
    0.028794187555304007 * texture2D(u_texture, vec2(coords.x, coords.y + offset6)) +
    0.02769527460196242 * texture2D(u_texture, vec2(coords.x, coords.y + offset7)) +
    0.026472956359477513 * texture2D(u_texture, vec2(coords.x, coords.y + offset8)) +
    0.02514751283981269 * texture2D(u_texture, vec2(coords.x, coords.y + offset9)) +
    0.02374014416962627 * texture2D(u_texture, vec2(coords.x, coords.y + offset10)) +
    0.02227241257354246 * texture2D(u_texture, vec2(coords.x, coords.y + offset11)) +
    0.02076570292838887 * texture2D(u_texture, vec2(coords.x, coords.y + offset12)) +
    0.01924072029507983 * texture2D(u_texture, vec2(coords.x, coords.y + offset13)) +
    0.017717040205760082 * texture2D(u_texture, vec2(coords.x, coords.y + offset14)) +
    0.016212724262197352 * texture2D(u_texture, vec2(coords.x, coords.y + offset15)) +
    0.014744009998103672 * texture2D(u_texture, vec2(coords.x, coords.y + offset16)) +
    0.013325080192478378 * texture2D(u_texture, vec2(coords.x, coords.y + offset17)) +
    0.011967913106226058 * texture2D(u_texture, vec2(coords.x, coords.y + offset18)) +
    0.010682211643494349 * texture2D(u_texture, vec2(coords.x, coords.y + offset19)) +
    0.009475406375021447 * texture2D(u_texture, vec2(coords.x, coords.y + offset20)) +
    0.008352724827403008 * texture2D(u_texture, vec2(coords.x, coords.y + offset21)) +
    0.0073173175207766235 * texture2D(u_texture, vec2(coords.x, coords.y + offset22)) +
    0.0063704299652471465 * texture2D(u_texture, vec2(coords.x, coords.y + offset23)) +
    0.005511609198954715 * texture2D(u_texture, vec2(coords.x, coords.y + offset24)) +
    0.00473893342663415 * texture2D(u_texture, vec2(coords.x, coords.y + offset25)) +
    0.00404925382541444 * texture2D(u_texture, vec2(coords.x, coords.y + offset26)) +
    0.0034384385311574546 * texture2D(u_texture, vec2(coords.x, coords.y + offset27)) +
    0.0029016100972999656 * texture2D(u_texture, vec2(coords.x, coords.y + offset28)) +
    0.0024333692176280773 * texture2D(u_texture, vec2(coords.x, coords.y + offset29)) +
    0.002027999116237829 * texture2D(u_texture, vec2(coords.x, coords.y + offset30)) +
    0.0016796466329463044 * texture2D(u_texture, vec2(coords.x, coords.y + offset31))
  );
}
