#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_dimensions;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy / u_dimensions.xy;

  float one_pixel = u_dimensions.z;
  float offset1 = one_pixel * 1.4782608695652173;
  float offset2 = one_pixel * 3.449275362318841;
  float offset3 = one_pixel * 5.420289855072464;
  float offset4 = one_pixel * 7.391304347826087;
  float offset5 = one_pixel * 9.36231884057971;

  gl_FragColor = (
    0.014208074336319735 * texture2D(u_texture, vec2(coords.x - offset5, coords.y)) +
    0.03829298667281616 * texture2D(u_texture, vec2(coords.x - offset4, coords.y)) +
    0.08120754070269633 * texture2D(u_texture, vec2(coords.x - offset3, coords.y)) +
    0.13621910053355513 * texture2D(u_texture, vec2(coords.x - offset2, coords.y)) +
    0.18136747665736602 * texture2D(u_texture, vec2(coords.x - offset1, coords.y)) +
    0.09740964219449326 * texture2D(u_texture, coords) +
    0.18136747665736602 * texture2D(u_texture, vec2(coords.x + offset1, coords.y)) +
    0.13621910053355513 * texture2D(u_texture, vec2(coords.x + offset2, coords.y)) +
    0.08120754070269633 * texture2D(u_texture, vec2(coords.x + offset3, coords.y)) +
    0.03829298667281616 * texture2D(u_texture, vec2(coords.x + offset4, coords.y)) +
    0.014208074336319735 * texture2D(u_texture, vec2(coords.x + offset5, coords.y))
  );
}
