#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.499853900847375;
  float offset2 = one_pixel * 3.4996591019772088;
  float offset3 = one_pixel * 5.499464303107042;
  float offset4 = one_pixel * 7.499269504236875;
  float offset5 = one_pixel * 9.49907470536671;
  float offset6 = one_pixel * 11.498879906496542;
  float offset7 = one_pixel * 13.498685107626375;
  float offset8 = one_pixel * 15.498490308756208;
  float offset9 = one_pixel * 17.49829550988604;
  float offset10 = one_pixel * 19.498100711015876;
  float offset11 = one_pixel * 21.49790591214571;
  float offset12 = one_pixel * 23.497711113275543;
  float offset13 = one_pixel * 25.497516314405377;
  float offset14 = one_pixel * 27.49732151553521;
  float offset15 = one_pixel * 29.497126716665043;
  float offset16 = one_pixel * 31.49693191779488;
  float offset17 = one_pixel * 33.49673711892471;
  float offset18 = one_pixel * 35.496542320054544;
  float offset19 = one_pixel * 37.496347521184376;
  float offset20 = one_pixel * 39.49615272231421;
  float offset21 = one_pixel * 41.495957923444045;
  float offset22 = one_pixel * 43.49576312457388;
  float offset23 = one_pixel * 45.49556832570371;
  float offset24 = one_pixel * 47.495373526833546;
  float offset25 = one_pixel * 49.49517872796338;
  float offset26 = one_pixel * 51.49498392909321;
  float offset27 = one_pixel * 53.49478913022305;
  float offset28 = one_pixel * 55.49459433135288;
  float offset29 = one_pixel * 57.49439953248271;
  float offset30 = one_pixel * 59.49420473361255;
  float offset31 = one_pixel * 61.49400993474238;
  float offset32 = one_pixel * 63.49381513587221;
  float offset33 = one_pixel * 65.49362033700204;
  float offset34 = one_pixel * 67.49342553813187;
  float offset35 = one_pixel * 69.49323073926172;
  float offset36 = one_pixel * 71.49303594039155;
  float offset37 = one_pixel * 73.49284114152138;
  float offset38 = one_pixel * 75.49264634265121;
  float offset39 = one_pixel * 77.49245154378104;
  float offset40 = one_pixel * 79.49225674491088;
  float offset41 = one_pixel * 81.4920619460407;
  float offset42 = one_pixel * 83.49186714717055;
  float offset43 = one_pixel * 85.49167234830038;
  float offset44 = one_pixel * 87.49147754943021;
  float offset45 = one_pixel * 89.49128275056005;
  float offset46 = one_pixel * 91.49108795168988;
  float offset47 = one_pixel * 93.49089315281971;
  float offset48 = one_pixel * 95.49069835394955;
  float offset49 = one_pixel * 97.49050355507939;
  float offset50 = one_pixel * 99.49030875620922;
  float offset51 = one_pixel * 101.49011395733905;
  float offset52 = one_pixel * 103.48991915846888;
  float offset53 = one_pixel * 105.48972435959871;
  float offset54 = one_pixel * 107.48952956072854;
  float offset55 = one_pixel * 109.48933476185839;
  float offset56 = one_pixel * 111.48913996298822;
  float offset57 = one_pixel * 113.48894516411805;
  float offset58 = one_pixel * 115.48875036524788;
  float offset59 = one_pixel * 117.48855556637771;
  float offset60 = one_pixel * 119.48836076750754;
  float offset61 = one_pixel * 121.48816596863738;
  float offset62 = one_pixel * 123.48797116976722;

  f_color = (
    0.0008184915902475593 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset62, coords.y)) +
    0.0009004758917404671 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset61, coords.y)) +
    0.0009891287941141305 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset60, coords.y)) +
    0.0010848170382548122 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset59, coords.y)) +
    0.0011879086953838454 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset58, coords.y)) +
    0.0012987708949173354 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset57, coords.y)) +
    0.0014177673423561143 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset56, coords.y)) +
    0.0015452556315268871 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset55, coords.y)) +
    0.001681584358244292 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset54, coords.y)) +
    0.001827090045376513 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset53, coords.y)) +
    0.0019820938923467315 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset52, coords.y)) +
    0.0021468983652568325 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset51, coords.y)) +
    0.002321783647041704 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset50, coords.y)) +
    0.0025070039703110414 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset49, coords.y)) +
    0.002702783858765722 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset48, coords.y)) +
    0.0029093143062389787 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset47, coords.y)) +
    0.003126748925457202 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset46, coords.y)) +
    0.0033552001014874188 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset45, coords.y)) +
    0.0035947351874830533 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset44, coords.y)) +
    0.003845372782700456 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset43, coords.y)) +
    0.0041070791347802855 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset42, coords.y)) +
    0.004379764709915782 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset41, coords.y)) +
    0.004663280975712341 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset40, coords.y)) +
    0.004957417442231049 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset39, coords.y)) +
    0.0052618990068590875 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset38, coords.y)) +
    0.005576383648223866 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset37, coords.y)) +
    0.005900460513333791 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset36, coords.y)) +
    0.006233648440462963 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset35, coords.y)) +
    0.006575394957984465 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset34, coords.y)) +
    0.006925075796391552 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset33, coords.y)) +
    0.007281994947132157 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset32, coords.y)) +
    0.00764538529763468 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset31, coords.y)) +
    0.008014409867047764 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset30, coords.y)) +
    0.008388163661790803 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset29, coords.y)) +
    0.008765676164063107 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset28, coords.y)) +
    0.009145914460046933 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset27, coords.y)) +
    0.009527787007732127 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset26, coords.y)) +
    0.009910148037166519 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset25, coords.y)) +
    0.01029180256858408 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset24, coords.y)) +
    0.010671512026377073 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset23, coords.y)) +
    0.011048000419360311 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset22, coords.y)) +
    0.011419961050331055 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset21, coords.y)) +
    0.011786063710666202 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset20, coords.y)) +
    0.012144962308729464 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset19, coords.y)) +
    0.012495302874294978 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset18, coords.y)) +
    0.012835731875137705 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset17, coords.y)) +
    0.01316490477649748 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset16, coords.y)) +
    0.01348149476938958 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset15, coords.y)) +
    0.013784201589797875 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset14, coords.y)) +
    0.014071760347725688 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset13, coords.y)) +
    0.014342950282960348 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset12, coords.y)) +
    0.01459660336328392 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset11, coords.y)) +
    0.014831612640773477 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset10, coords.y)) +
    0.0150469402828032 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset9, coords.y)) +
    0.015241625196395143 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset8, coords.y)) +
    0.015414790167656504 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset7, coords.y)) +
    0.015565648442163052 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset6, coords.y)) +
    0.0156935096772585 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset5, coords.y)) +
    0.01579778520327978 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset4, coords.y)) +
    0.01587799253761461 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset3, coords.y)) +
    0.0159337591031625 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset2, coords.y)) +
    0.015964825111102726 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset1, coords.y)) +
    0.007986300573788766 * texture(sampler2D(t_input, s_input), coords) +
    0.015964825111102726 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset1, coords.y)) +
    0.0159337591031625 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset2, coords.y)) +
    0.01587799253761461 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset3, coords.y)) +
    0.01579778520327978 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset4, coords.y)) +
    0.0156935096772585 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset5, coords.y)) +
    0.015565648442163052 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset6, coords.y)) +
    0.015414790167656504 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset7, coords.y)) +
    0.015241625196395143 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset8, coords.y)) +
    0.0150469402828032 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset9, coords.y)) +
    0.014831612640773477 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset10, coords.y)) +
    0.01459660336328392 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset11, coords.y)) +
    0.014342950282960348 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset12, coords.y)) +
    0.014071760347725688 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset13, coords.y)) +
    0.013784201589797875 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset14, coords.y)) +
    0.01348149476938958 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset15, coords.y)) +
    0.01316490477649748 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset16, coords.y)) +
    0.012835731875137705 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset17, coords.y)) +
    0.012495302874294978 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset18, coords.y)) +
    0.012144962308729464 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset19, coords.y)) +
    0.011786063710666202 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset20, coords.y)) +
    0.011419961050331055 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset21, coords.y)) +
    0.011048000419360311 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset22, coords.y)) +
    0.010671512026377073 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset23, coords.y)) +
    0.01029180256858408 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset24, coords.y)) +
    0.009910148037166519 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset25, coords.y)) +
    0.009527787007732127 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset26, coords.y)) +
    0.009145914460046933 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset27, coords.y)) +
    0.008765676164063107 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset28, coords.y)) +
    0.008388163661790803 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset29, coords.y)) +
    0.008014409867047764 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset30, coords.y)) +
    0.00764538529763468 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset31, coords.y)) +
    0.007281994947132157 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset32, coords.y)) +
    0.006925075796391552 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset33, coords.y)) +
    0.006575394957984465 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset34, coords.y)) +
    0.006233648440462963 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset35, coords.y)) +
    0.005900460513333791 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset36, coords.y)) +
    0.005576383648223866 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset37, coords.y)) +
    0.0052618990068590875 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset38, coords.y)) +
    0.004957417442231049 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset39, coords.y)) +
    0.004663280975712341 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset40, coords.y)) +
    0.004379764709915782 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset41, coords.y)) +
    0.0041070791347802855 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset42, coords.y)) +
    0.003845372782700456 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset43, coords.y)) +
    0.0035947351874830533 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset44, coords.y)) +
    0.0033552001014874188 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset45, coords.y)) +
    0.003126748925457202 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset46, coords.y)) +
    0.0029093143062389787 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset47, coords.y)) +
    0.002702783858765722 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset48, coords.y)) +
    0.0025070039703110414 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset49, coords.y)) +
    0.002321783647041704 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset50, coords.y)) +
    0.0021468983652568325 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset51, coords.y)) +
    0.0019820938923467315 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset52, coords.y)) +
    0.001827090045376513 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset53, coords.y)) +
    0.001681584358244292 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset54, coords.y)) +
    0.0015452556315268871 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset55, coords.y)) +
    0.0014177673423561143 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset56, coords.y)) +
    0.0012987708949173354 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset57, coords.y)) +
    0.0011879086953838454 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset58, coords.y)) +
    0.0010848170382548122 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset59, coords.y)) +
    0.0009891287941141305 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset60, coords.y)) +
    0.0009004758917404671 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset61, coords.y)) +
    0.0008184915902475593 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset62, coords.y))
  );
}
