#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_scaling;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.4887218045112782;
  float offset2 = one_pixel * 3.473684210526316;
  float offset3 = one_pixel * 5.458646616541353;
  float offset4 = one_pixel * 7.443609022556391;
  float offset5 = one_pixel * 9.428571428571429;
  float offset6 = one_pixel * 11.413533834586467;
  float offset7 = one_pixel * 13.398496240601503;

  gl_FragColor = (
    0.009030680988688426 * texture2D(u_texture, vec2(coords.x - offset7, coords.y)) +
    0.019216802642596245 * texture2D(u_texture, vec2(coords.x - offset6, coords.y)) +
    0.036157931288042934 * texture2D(u_texture, vec2(coords.x - offset5, coords.y)) +
    0.060227997762082035 * texture2D(u_texture, vec2(coords.x - offset4, coords.y)) +
    0.08889389177889813 * texture2D(u_texture, vec2(coords.x - offset3, coords.y)) +
    0.11634039292722152 * texture2D(u_texture, vec2(coords.x - offset2, coords.y)) +
    0.13507790813425 * texture2D(u_texture, vec2(coords.x - offset1, coords.y)) +
    0.07010878895644143 * texture2D(u_texture, coords) +
    0.13507790813425 * texture2D(u_texture, vec2(coords.x + offset1, coords.y)) +
    0.11634039292722152 * texture2D(u_texture, vec2(coords.x + offset2, coords.y)) +
    0.08889389177889813 * texture2D(u_texture, vec2(coords.x + offset3, coords.y)) +
    0.060227997762082035 * texture2D(u_texture, vec2(coords.x + offset4, coords.y)) +
    0.036157931288042934 * texture2D(u_texture, vec2(coords.x + offset5, coords.y)) +
    0.019216802642596245 * texture2D(u_texture, vec2(coords.x + offset6, coords.y)) +
    0.009030680988688426 * texture2D(u_texture, vec2(coords.x + offset7, coords.y))
  );
}
