#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.4931506849315068;
  float offset2 = one_pixel * 3.4840182648401825;
  float offset3 = one_pixel * 5.474885844748859;
  float offset4 = one_pixel * 7.465753424657534;
  float offset5 = one_pixel * 9.45662100456621;
  float offset6 = one_pixel * 11.447488584474886;
  float offset7 = one_pixel * 13.438356164383562;
  float offset8 = one_pixel * 15.429223744292237;
  float offset9 = one_pixel * 17.420091324200914;

  f_color = (
    0.006656591401043247 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset9, coords.y)) +
    0.012184714664778544 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset8, coords.y)) +
    0.020708670757024938 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset7, coords.y)) +
    0.032690333829151715 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset6, coords.y)) +
    0.04794582294942252 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset5, coords.y)) +
    0.0653518972874967 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset4, coords.y)) +
    0.08280021937881864 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset3, coords.y)) +
    0.0975301775432446 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset2, coords.y)) +
    0.10681394314531875 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset1, coords.y)) +
    0.0546352580874007 * texture(sampler2D(t_input, s_input), coords) +
    0.10681394314531875 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset1, coords.y)) +
    0.0975301775432446 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset2, coords.y)) +
    0.08280021937881864 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset3, coords.y)) +
    0.0653518972874967 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset4, coords.y)) +
    0.04794582294942252 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset5, coords.y)) +
    0.032690333829151715 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset6, coords.y)) +
    0.020708670757024938 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset7, coords.y)) +
    0.012184714664778544 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset8, coords.y)) +
    0.006656591401043247 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset9, coords.y))
  );
}
