#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_scaling;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.4982698961937717;
  float offset2 = one_pixel * 3.4959630911188007;
  float offset3 = one_pixel * 5.493656286043829;
  float offset4 = one_pixel * 7.491349480968858;
  float offset5 = one_pixel * 9.489042675893886;
  float offset6 = one_pixel * 11.486735870818915;
  float offset7 = one_pixel * 13.484429065743944;
  float offset8 = one_pixel * 15.482122260668973;
  float offset9 = one_pixel * 17.479815455594004;
  float offset10 = one_pixel * 19.47750865051903;
  float offset11 = one_pixel * 21.47520184544406;
  float offset12 = one_pixel * 23.47289504036909;
  float offset13 = one_pixel * 25.470588235294116;
  float offset14 = one_pixel * 27.468281430219147;
  float offset15 = one_pixel * 29.465974625144174;
  float offset16 = one_pixel * 31.463667820069205;
  float offset17 = one_pixel * 33.46136101499423;
  float offset18 = one_pixel * 35.45905420991926;

  gl_FragColor = (
    0.002999397390319723 * texture2D(u_texture, vec2(coords.x - offset18, coords.y)) +
    0.004124960726792335 * texture2D(u_texture, vec2(coords.x - offset17, coords.y)) +
    0.005568679069031412 * texture2D(u_texture, vec2(coords.x - offset16, coords.y)) +
    0.007379666093004307 * texture2D(u_texture, vec2(coords.x - offset15, coords.y)) +
    0.009600163323543024 * texture2D(u_texture, vec2(coords.x - offset14, coords.y)) +
    0.012259783653650177 * texture2D(u_texture, vec2(coords.x - offset13, coords.y)) +
    0.01536928999485746 * texture2D(u_texture, vec2(coords.x - offset12, coords.y)) +
    0.01891454114171176 * texture2D(u_texture, vec2(coords.x - offset11, coords.y)) +
    0.022851392331610335 * texture2D(u_texture, vec2(coords.x - offset10, coords.y)) +
    0.027102407832780385 * texture2D(u_texture, vec2(coords.x - offset9, coords.y)) +
    0.03155619238386963 * texture2D(u_texture, vec2(coords.x - offset8, coords.y)) +
    0.036069958008865456 * texture2D(u_texture, vec2(coords.x - offset7, coords.y)) +
    0.040475616443378076 * texture2D(u_texture, vec2(coords.x - offset6, coords.y)) +
    0.0445892563053807 * texture2D(u_texture, vec2(coords.x - offset5, coords.y)) +
    0.04822338536388497 * texture2D(u_texture, vec2(coords.x - offset4, coords.y)) +
    0.05120086725474534 * texture2D(u_texture, vec2(coords.x - offset3, coords.y)) +
    0.05336913946699704 * texture2D(u_texture, vec2(coords.x - offset2, coords.y)) +
    0.05461313526320078 * texture2D(u_texture, vec2(coords.x - offset1, coords.y)) +
    0.02746433590475419 * texture2D(u_texture, coords) +
    0.05461313526320078 * texture2D(u_texture, vec2(coords.x + offset1, coords.y)) +
    0.05336913946699704 * texture2D(u_texture, vec2(coords.x + offset2, coords.y)) +
    0.05120086725474534 * texture2D(u_texture, vec2(coords.x + offset3, coords.y)) +
    0.04822338536388497 * texture2D(u_texture, vec2(coords.x + offset4, coords.y)) +
    0.0445892563053807 * texture2D(u_texture, vec2(coords.x + offset5, coords.y)) +
    0.040475616443378076 * texture2D(u_texture, vec2(coords.x + offset6, coords.y)) +
    0.036069958008865456 * texture2D(u_texture, vec2(coords.x + offset7, coords.y)) +
    0.03155619238386963 * texture2D(u_texture, vec2(coords.x + offset8, coords.y)) +
    0.027102407832780385 * texture2D(u_texture, vec2(coords.x + offset9, coords.y)) +
    0.022851392331610335 * texture2D(u_texture, vec2(coords.x + offset10, coords.y)) +
    0.01891454114171176 * texture2D(u_texture, vec2(coords.x + offset11, coords.y)) +
    0.01536928999485746 * texture2D(u_texture, vec2(coords.x + offset12, coords.y)) +
    0.012259783653650177 * texture2D(u_texture, vec2(coords.x + offset13, coords.y)) +
    0.009600163323543024 * texture2D(u_texture, vec2(coords.x + offset14, coords.y)) +
    0.007379666093004307 * texture2D(u_texture, vec2(coords.x + offset15, coords.y)) +
    0.005568679069031412 * texture2D(u_texture, vec2(coords.x + offset16, coords.y)) +
    0.004124960726792335 * texture2D(u_texture, vec2(coords.x + offset17, coords.y)) +
    0.002999397390319723 * texture2D(u_texture, vec2(coords.x + offset18, coords.y))
  );
}
