#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.499332443257677;
  float offset2 = one_pixel * 3.498442367601246;
  float offset3 = one_pixel * 5.497552291944816;
  float offset4 = one_pixel * 7.496662216288384;
  float offset5 = one_pixel * 9.495772140631953;
  float offset6 = one_pixel * 11.494882064975522;
  float offset7 = one_pixel * 13.493991989319092;
  float offset8 = one_pixel * 15.493101913662661;
  float offset9 = one_pixel * 17.49221183800623;
  float offset10 = one_pixel * 19.4913217623498;
  float offset11 = one_pixel * 21.49043168669337;
  float offset12 = one_pixel * 23.489541611036937;
  float offset13 = one_pixel * 25.48865153538051;
  float offset14 = one_pixel * 27.487761459724076;
  float offset15 = one_pixel * 29.486871384067644;
  float offset16 = one_pixel * 31.485981308411215;
  float offset17 = one_pixel * 33.48509123275478;
  float offset18 = one_pixel * 35.484201157098354;
  float offset19 = one_pixel * 37.483311081441926;
  float offset20 = one_pixel * 39.48242100578549;
  float offset21 = one_pixel * 41.48153093012906;
  float offset22 = one_pixel * 43.48064085447263;
  float offset23 = one_pixel * 45.4797507788162;
  float offset24 = one_pixel * 47.47886070315977;
  float offset25 = one_pixel * 49.47797062750334;
  float offset26 = one_pixel * 51.47708055184691;
  float offset27 = one_pixel * 53.476190476190474;
  float offset28 = one_pixel * 55.475300400534046;
  float offset29 = one_pixel * 57.47441032487762;

  f_color = (
    0.001798888711234053 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset29, coords.y)) +
    0.002199887789807216 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset28, coords.y)) +
    0.002671149170355061 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset27, coords.y)) +
    0.0032203099231131616 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset26, coords.y)) +
    0.0038547802966659647 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset25, coords.y)) +
    0.0045814665354225945 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset24, coords.y)) +
    0.005406457723893273 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset23, coords.y)) +
    0.006334684142160166 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset22, coords.y)) +
    0.007369557587097988 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset21, coords.y)) +
    0.008512606997066453 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset20, coords.y)) +
    0.009763125299350415 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset19, coords.y)) +
    0.011117845449693879 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset18, coords.y)) +
    0.012570664923323349 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset17, coords.y)) +
    0.014112438238959446 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset16, coords.y)) +
    0.015730856284685055 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset15, coords.y)) +
    0.017410429161476046 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset14, coords.y)) +
    0.019132585939453824 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset13, coords.y)) +
    0.020875900197376496 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset12, coords.y)) +
    0.02261644464877162 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset11, coords.y)) +
    0.024328271805265093 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset10, coords.y)) +
    0.02598401083112546 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset9, coords.y)) +
    0.027555563911046972 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset8, coords.y)) +
    0.029014879033419188 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset7, coords.y)) +
    0.03033477053831639 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset6, coords.y)) +
    0.031489754518705525 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset5, coords.y)) +
    0.032456863555373035 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset4, coords.y)) +
    0.03321640457338722 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset3, coords.y)) +
    0.033752624968932325 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset2, coords.y)) +
    0.03405425556728941 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset1, coords.y)) +
    0.017065043354466666 * texture(sampler2D(t_input, s_input), coords) +
    0.03405425556728941 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset1, coords.y)) +
    0.033752624968932325 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset2, coords.y)) +
    0.03321640457338722 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset3, coords.y)) +
    0.032456863555373035 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset4, coords.y)) +
    0.031489754518705525 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset5, coords.y)) +
    0.03033477053831639 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset6, coords.y)) +
    0.029014879033419188 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset7, coords.y)) +
    0.027555563911046972 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset8, coords.y)) +
    0.02598401083112546 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset9, coords.y)) +
    0.024328271805265093 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset10, coords.y)) +
    0.02261644464877162 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset11, coords.y)) +
    0.020875900197376496 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset12, coords.y)) +
    0.019132585939453824 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset13, coords.y)) +
    0.017410429161476046 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset14, coords.y)) +
    0.015730856284685055 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset15, coords.y)) +
    0.014112438238959446 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset16, coords.y)) +
    0.012570664923323349 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset17, coords.y)) +
    0.011117845449693879 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset18, coords.y)) +
    0.009763125299350415 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset19, coords.y)) +
    0.008512606997066453 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset20, coords.y)) +
    0.007369557587097988 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset21, coords.y)) +
    0.006334684142160166 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset22, coords.y)) +
    0.005406457723893273 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset23, coords.y)) +
    0.0045814665354225945 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset24, coords.y)) +
    0.0038547802966659647 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset25, coords.y)) +
    0.0032203099231131616 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset26, coords.y)) +
    0.002671149170355061 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset27, coords.y)) +
    0.002199887789807216 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset28, coords.y)) +
    0.001798888711234053 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset29, coords.y))
  );
}
