#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_scaling;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.4993762993762993;
  float offset2 = one_pixel * 3.4985446985446984;
  float offset3 = one_pixel * 5.497713097713098;
  float offset4 = one_pixel * 7.496881496881497;
  float offset5 = one_pixel * 9.496049896049897;
  float offset6 = one_pixel * 11.495218295218296;
  float offset7 = one_pixel * 13.494386694386694;
  float offset8 = one_pixel * 15.493555093555093;
  float offset9 = one_pixel * 17.492723492723492;
  float offset10 = one_pixel * 19.491891891891893;
  float offset11 = one_pixel * 21.49106029106029;
  float offset12 = one_pixel * 23.49022869022869;
  float offset13 = one_pixel * 25.48939708939709;
  float offset14 = one_pixel * 27.488565488565488;
  float offset15 = one_pixel * 29.48773388773389;
  float offset16 = one_pixel * 31.486902286902286;
  float offset17 = one_pixel * 33.48607068607068;
  float offset18 = one_pixel * 35.48523908523909;
  float offset19 = one_pixel * 37.484407484407484;
  float offset20 = one_pixel * 39.48357588357588;
  float offset21 = one_pixel * 41.482744282744285;
  float offset22 = one_pixel * 43.48191268191268;
  float offset23 = one_pixel * 45.48108108108108;
  float offset24 = one_pixel * 47.48024948024948;
  float offset25 = one_pixel * 49.47941787941788;
  float offset26 = one_pixel * 51.47858627858628;
  float offset27 = one_pixel * 53.477754677754675;
  float offset28 = one_pixel * 55.47692307692308;
  float offset29 = one_pixel * 57.476091476091476;
  float offset30 = one_pixel * 59.47525987525987;

  gl_FragColor = (
    0.0017366740973558635 * texture2D(u_texture, vec2(coords.x - offset30, coords.y)) +
    0.002109897012244151 * texture2D(u_texture, vec2(coords.x - offset29, coords.y)) +
    0.00254629957077754 * texture2D(u_texture, vec2(coords.x - offset28, coords.y)) +
    0.0030525550084969724 * texture2D(u_texture, vec2(coords.x - offset27, coords.y)) +
    0.003635161416381678 * texture2D(u_texture, vec2(coords.x - offset26, coords.y)) +
    0.004300218480042031 * texture2D(u_texture, vec2(coords.x - offset25, coords.y)) +
    0.005053175324527367 * texture2D(u_texture, vec2(coords.x - offset24, coords.y)) +
    0.005898554888865392 * texture2D(u_texture, vec2(coords.x - offset23, coords.y)) +
    0.006839662442852512 * texture2D(u_texture, vec2(coords.x - offset22, coords.y)) +
    0.00787828800805178 * texture2D(u_texture, vec2(coords.x - offset21, coords.y)) +
    0.009014414410285587 * texture2D(u_texture, vec2(coords.x - offset20, coords.y)) +
    0.010245944314919844 * texture2D(u_texture, vec2(coords.x - offset19, coords.y)) +
    0.011568460719875367 * texture2D(u_texture, vec2(coords.x - offset18, coords.y)) +
    0.01297503585576996 * texture2D(u_texture, vec2(coords.x - offset17, coords.y)) +
    0.014456103142466162 * texture2D(u_texture, vec2(coords.x - offset16, coords.y)) +
    0.015999405687650316 * texture2D(u_texture, vec2(coords.x - offset15, coords.y)) +
    0.01759003274540213 * texture2D(u_texture, vec2(coords.x - offset14, coords.y)) +
    0.019210552598444418 * texture2D(u_texture, vec2(coords.x - offset13, coords.y)) +
    0.020841246568069193 * texture2D(u_texture, vec2(coords.x - offset12, coords.y)) +
    0.022460444436813616 * texture2D(u_texture, vec2(coords.x - offset11, coords.y)) +
    0.024044956698016755 * texture2D(u_texture, vec2(coords.x - offset10, coords.y)) +
    0.025570593982178893 * texture2D(u_texture, vec2(coords.x - offset9, coords.y)) +
    0.027012759048216844 * texture2D(u_texture, vec2(coords.x - offset8, coords.y)) +
    0.028347092181788533 * texture2D(u_texture, vec2(coords.x - offset7, coords.y)) +
    0.02955014702217729 * texture2D(u_texture, vec2(coords.x - offset6, coords.y)) +
    0.03060007102548133 * texture2D(u_texture, vec2(coords.x - offset5, coords.y)) +
    0.03147726319629652 * texture2D(u_texture, vec2(coords.x - offset4, coords.y)) +
    0.032164981543344295 * texture2D(u_texture, vec2(coords.x - offset3, coords.y)) +
    0.03264987401100974 * texture2D(u_texture, vec2(coords.x - offset2, coords.y)) +
    0.032922409387329786 * texture2D(u_texture, vec2(coords.x - offset1, coords.y)) +
    0.01649545034973627 * texture2D(u_texture, coords) +
    0.032922409387329786 * texture2D(u_texture, vec2(coords.x + offset1, coords.y)) +
    0.03264987401100974 * texture2D(u_texture, vec2(coords.x + offset2, coords.y)) +
    0.032164981543344295 * texture2D(u_texture, vec2(coords.x + offset3, coords.y)) +
    0.03147726319629652 * texture2D(u_texture, vec2(coords.x + offset4, coords.y)) +
    0.03060007102548133 * texture2D(u_texture, vec2(coords.x + offset5, coords.y)) +
    0.02955014702217729 * texture2D(u_texture, vec2(coords.x + offset6, coords.y)) +
    0.028347092181788533 * texture2D(u_texture, vec2(coords.x + offset7, coords.y)) +
    0.027012759048216844 * texture2D(u_texture, vec2(coords.x + offset8, coords.y)) +
    0.025570593982178893 * texture2D(u_texture, vec2(coords.x + offset9, coords.y)) +
    0.024044956698016755 * texture2D(u_texture, vec2(coords.x + offset10, coords.y)) +
    0.022460444436813616 * texture2D(u_texture, vec2(coords.x + offset11, coords.y)) +
    0.020841246568069193 * texture2D(u_texture, vec2(coords.x + offset12, coords.y)) +
    0.019210552598444418 * texture2D(u_texture, vec2(coords.x + offset13, coords.y)) +
    0.01759003274540213 * texture2D(u_texture, vec2(coords.x + offset14, coords.y)) +
    0.015999405687650316 * texture2D(u_texture, vec2(coords.x + offset15, coords.y)) +
    0.014456103142466162 * texture2D(u_texture, vec2(coords.x + offset16, coords.y)) +
    0.01297503585576996 * texture2D(u_texture, vec2(coords.x + offset17, coords.y)) +
    0.011568460719875367 * texture2D(u_texture, vec2(coords.x + offset18, coords.y)) +
    0.010245944314919844 * texture2D(u_texture, vec2(coords.x + offset19, coords.y)) +
    0.009014414410285587 * texture2D(u_texture, vec2(coords.x + offset20, coords.y)) +
    0.00787828800805178 * texture2D(u_texture, vec2(coords.x + offset21, coords.y)) +
    0.006839662442852512 * texture2D(u_texture, vec2(coords.x + offset22, coords.y)) +
    0.005898554888865392 * texture2D(u_texture, vec2(coords.x + offset23, coords.y)) +
    0.005053175324527367 * texture2D(u_texture, vec2(coords.x + offset24, coords.y)) +
    0.004300218480042031 * texture2D(u_texture, vec2(coords.x + offset25, coords.y)) +
    0.003635161416381678 * texture2D(u_texture, vec2(coords.x + offset26, coords.y)) +
    0.0030525550084969724 * texture2D(u_texture, vec2(coords.x + offset27, coords.y)) +
    0.00254629957077754 * texture2D(u_texture, vec2(coords.x + offset28, coords.y)) +
    0.002109897012244151 * texture2D(u_texture, vec2(coords.x + offset29, coords.y)) +
    0.0017366740973558635 * texture2D(u_texture, vec2(coords.x + offset30, coords.y))
  );
}
