#ifdef GL_FRAGMENT_PRECISION_HIGH
  precision highp float;
#else
  precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec4 u_scaling;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.4996659986639946;
  float offset2 = one_pixel * 3.499220663549321;
  float offset3 = one_pixel * 5.498775328434647;
  float offset4 = one_pixel * 7.498329993319973;
  float offset5 = one_pixel * 9.4978846582053;
  float offset6 = one_pixel * 11.497439323090626;
  float offset7 = one_pixel * 13.496993987975952;
  float offset8 = one_pixel * 15.496548652861279;
  float offset9 = one_pixel * 17.496103317746606;
  float offset10 = one_pixel * 19.49565798263193;
  float offset11 = one_pixel * 21.495212647517256;
  float offset12 = one_pixel * 23.494767312402583;
  float offset13 = one_pixel * 25.49432197728791;
  float offset14 = one_pixel * 27.493876642173234;
  float offset15 = one_pixel * 29.49343130705856;
  float offset16 = one_pixel * 31.492985971943888;
  float offset17 = one_pixel * 33.49254063682921;
  float offset18 = one_pixel * 35.49209530171454;
  float offset19 = one_pixel * 37.491649966599866;
  float offset20 = one_pixel * 39.49120463148519;
  float offset21 = one_pixel * 41.49075929637052;
  float offset22 = one_pixel * 43.49031396125584;
  float offset23 = one_pixel * 45.489868626141174;
  float offset24 = one_pixel * 47.4894232910265;
  float offset25 = one_pixel * 49.48897795591182;
  float offset26 = one_pixel * 51.48853262079715;
  float offset27 = one_pixel * 53.488087285682475;
  float offset28 = one_pixel * 55.487641950567806;
  float offset29 = one_pixel * 57.48719661545313;
  float offset30 = one_pixel * 59.48675128033845;
  float offset31 = one_pixel * 61.48630594522378;
  float offset32 = one_pixel * 63.48586061010911;
  float offset33 = one_pixel * 65.48541527499444;
  float offset34 = one_pixel * 67.48496993987976;
  float offset35 = one_pixel * 69.48452460476508;
  float offset36 = one_pixel * 71.48407926965041;
  float offset37 = one_pixel * 73.48363393453573;
  float offset38 = one_pixel * 75.48318859942107;
  float offset39 = one_pixel * 77.4827432643064;
  float offset40 = one_pixel * 79.48229792919172;
  float offset41 = one_pixel * 81.48185259407704;

  gl_FragColor = (
    0.001253587976128632 * texture2D(u_texture, vec2(coords.x - offset41, coords.y)) +
    0.0014469201296479469 * texture2D(u_texture, vec2(coords.x - offset40, coords.y)) +
    0.0016641231046472735 * texture2D(u_texture, vec2(coords.x - offset39, coords.y)) +
    0.0019071181077321242 * texture2D(u_texture, vec2(coords.x - offset38, coords.y)) +
    0.0021778154309882837 * texture2D(u_texture, vec2(coords.x - offset37, coords.y)) +
    0.002478083778881684 * texture2D(u_texture, vec2(coords.x - offset36, coords.y)) +
    0.0028097159795235555 * texture2D(u_texture, vec2(coords.x - offset35, coords.y)) +
    0.0031743913490501815 * texture2D(u_texture, vec2(coords.x - offset34, coords.y)) +
    0.0035736351040786107 * texture2D(u_texture, vec2(coords.x - offset33, coords.y)) +
    0.0040087753487990175 * texture2D(u_texture, vec2(coords.x - offset32, coords.y)) +
    0.004480898296508225 * texture2D(u_texture, vec2(coords.x - offset31, coords.y)) +
    0.004990802515973829 * texture2D(u_texture, vec2(coords.x - offset30, coords.y)) +
    0.005538953116185247 * texture2D(u_texture, vec2(coords.x - offset29, coords.y)) +
    0.0061254368937203214 * texture2D(u_texture, vec2(coords.x - offset28, coords.y)) +
    0.006749919559910828 * texture2D(u_texture, vec2(coords.x - offset27, coords.y)) +
    0.007411606235054691 * texture2D(u_texture, vec2(coords.x - offset26, coords.y)) +
    0.008109206439193597 * texture2D(u_texture, vec2(coords.x - offset25, coords.y)) +
    0.008840904819048827 * texture2D(u_texture, vec2(coords.x - offset24, coords.y)) +
    0.009604338824916488 * texture2D(u_texture, vec2(coords.x - offset23, coords.y)) +
    0.01039658448695676 * texture2D(u_texture, vec2(coords.x - offset22, coords.y)) +
    0.011214151335827635 * texture2D(u_texture, vec2(coords.x - offset21, coords.y)) +
    0.012052987367808762 * texture2D(u_texture, vec2(coords.x - offset20, coords.y)) +
    0.012908494770704843 * texture2D(u_texture, vec2(coords.x - offset19, coords.y)) +
    0.013775556906728074 * texture2D(u_texture, vec2(coords.x - offset18, coords.y)) +
    0.014648576796619107 * texture2D(u_texture, vec2(coords.x - offset17, coords.y)) +
    0.015521527071372514 * texture2D(u_texture, vec2(coords.x - offset16, coords.y)) +
    0.016388011061373598 * texture2D(u_texture, vec2(coords.x - offset15, coords.y)) +
    0.017241334386014842 * texture2D(u_texture, vec2(coords.x - offset14, coords.y)) +
    0.01807458609936776 * texture2D(u_texture, vec2(coords.x - offset13, coords.y)) +
    0.01888072814928722 * texture2D(u_texture, vec2(coords.x - offset12, coords.y)) +
    0.01965269162872572 * texture2D(u_texture, vec2(coords.x - offset11, coords.y)) +
    0.020383478049199925 * texture2D(u_texture, vec2(coords.x - offset10, coords.y)) +
    0.0210662636568939 * texture2D(u_texture, vec2(coords.x - offset9, coords.y)) +
    0.02169450465045077 * texture2D(u_texture, vec2(coords.x - offset8, coords.y)) +
    0.022262041053394008 * texture2D(u_texture, vec2(coords.x - offset7, coords.y)) +
    0.022763196948927023 * texture2D(u_texture, vec2(coords.x - offset6, coords.y)) +
    0.023192874804194734 * texture2D(u_texture, vec2(coords.x - offset5, coords.y)) +
    0.023546641696361996 * texture2D(u_texture, vec2(coords.x - offset4, coords.y)) +
    0.023820805403154878 * texture2D(u_texture, vec2(coords.x - offset3, coords.y)) +
    0.02401247853255199 * texture2D(u_texture, vec2(coords.x - offset2, coords.y)) +
    0.024119629134551856 * texture2D(u_texture, vec2(coords.x - offset1, coords.y)) +
    0.012073245999085446 * texture2D(u_texture, coords) +
    0.024119629134551856 * texture2D(u_texture, vec2(coords.x + offset1, coords.y)) +
    0.02401247853255199 * texture2D(u_texture, vec2(coords.x + offset2, coords.y)) +
    0.023820805403154878 * texture2D(u_texture, vec2(coords.x + offset3, coords.y)) +
    0.023546641696361996 * texture2D(u_texture, vec2(coords.x + offset4, coords.y)) +
    0.023192874804194734 * texture2D(u_texture, vec2(coords.x + offset5, coords.y)) +
    0.022763196948927023 * texture2D(u_texture, vec2(coords.x + offset6, coords.y)) +
    0.022262041053394008 * texture2D(u_texture, vec2(coords.x + offset7, coords.y)) +
    0.02169450465045077 * texture2D(u_texture, vec2(coords.x + offset8, coords.y)) +
    0.0210662636568939 * texture2D(u_texture, vec2(coords.x + offset9, coords.y)) +
    0.020383478049199925 * texture2D(u_texture, vec2(coords.x + offset10, coords.y)) +
    0.01965269162872572 * texture2D(u_texture, vec2(coords.x + offset11, coords.y)) +
    0.01888072814928722 * texture2D(u_texture, vec2(coords.x + offset12, coords.y)) +
    0.01807458609936776 * texture2D(u_texture, vec2(coords.x + offset13, coords.y)) +
    0.017241334386014842 * texture2D(u_texture, vec2(coords.x + offset14, coords.y)) +
    0.016388011061373598 * texture2D(u_texture, vec2(coords.x + offset15, coords.y)) +
    0.015521527071372514 * texture2D(u_texture, vec2(coords.x + offset16, coords.y)) +
    0.014648576796619107 * texture2D(u_texture, vec2(coords.x + offset17, coords.y)) +
    0.013775556906728074 * texture2D(u_texture, vec2(coords.x + offset18, coords.y)) +
    0.012908494770704843 * texture2D(u_texture, vec2(coords.x + offset19, coords.y)) +
    0.012052987367808762 * texture2D(u_texture, vec2(coords.x + offset20, coords.y)) +
    0.011214151335827635 * texture2D(u_texture, vec2(coords.x + offset21, coords.y)) +
    0.01039658448695676 * texture2D(u_texture, vec2(coords.x + offset22, coords.y)) +
    0.009604338824916488 * texture2D(u_texture, vec2(coords.x + offset23, coords.y)) +
    0.008840904819048827 * texture2D(u_texture, vec2(coords.x + offset24, coords.y)) +
    0.008109206439193597 * texture2D(u_texture, vec2(coords.x + offset25, coords.y)) +
    0.007411606235054691 * texture2D(u_texture, vec2(coords.x + offset26, coords.y)) +
    0.006749919559910828 * texture2D(u_texture, vec2(coords.x + offset27, coords.y)) +
    0.0061254368937203214 * texture2D(u_texture, vec2(coords.x + offset28, coords.y)) +
    0.005538953116185247 * texture2D(u_texture, vec2(coords.x + offset29, coords.y)) +
    0.004990802515973829 * texture2D(u_texture, vec2(coords.x + offset30, coords.y)) +
    0.004480898296508225 * texture2D(u_texture, vec2(coords.x + offset31, coords.y)) +
    0.0040087753487990175 * texture2D(u_texture, vec2(coords.x + offset32, coords.y)) +
    0.0035736351040786107 * texture2D(u_texture, vec2(coords.x + offset33, coords.y)) +
    0.0031743913490501815 * texture2D(u_texture, vec2(coords.x + offset34, coords.y)) +
    0.0028097159795235555 * texture2D(u_texture, vec2(coords.x + offset35, coords.y)) +
    0.002478083778881684 * texture2D(u_texture, vec2(coords.x + offset36, coords.y)) +
    0.0021778154309882837 * texture2D(u_texture, vec2(coords.x + offset37, coords.y)) +
    0.0019071181077321242 * texture2D(u_texture, vec2(coords.x + offset38, coords.y)) +
    0.0016641231046472735 * texture2D(u_texture, vec2(coords.x + offset39, coords.y)) +
    0.0014469201296479469 * texture2D(u_texture, vec2(coords.x + offset40, coords.y)) +
    0.001253587976128632 * texture2D(u_texture, vec2(coords.x + offset41, coords.y))
  );
}
