#version 310 es

precision mediump float;
precision mediump sampler;

layout(set=0, binding=0) uniform _0 { vec4 u_scaling; };

layout(set=0, binding=1) uniform texture2D t_input;
layout(set=0, binding=2) uniform sampler s_input;

layout(location=0) out vec4 f_color;

// Generated by https://github.com/tuzz/gaussian_blur_generator

void main() {
  vec2 coords = gl_FragCoord.xy * u_scaling.xy;

  float one_pixel = u_scaling.x;
  float offset1 = one_pixel * 1.4996817313812858;
  float offset2 = one_pixel * 3.499257373223;
  float offset3 = one_pixel * 5.498833015064714;
  float offset4 = one_pixel * 7.498408656906429;
  float offset5 = one_pixel * 9.497984298748143;
  float offset6 = one_pixel * 11.497559940589857;
  float offset7 = one_pixel * 13.497135582431572;
  float offset8 = one_pixel * 15.496711224273287;
  float offset9 = one_pixel * 17.496286866115;
  float offset10 = one_pixel * 19.495862507956716;
  float offset11 = one_pixel * 21.49543814979843;
  float offset12 = one_pixel * 23.495013791640144;
  float offset13 = one_pixel * 25.49458943348186;
  float offset14 = one_pixel * 27.494165075323572;
  float offset15 = one_pixel * 29.493740717165288;
  float offset16 = one_pixel * 31.493316359007;
  float offset17 = one_pixel * 33.49289200084872;
  float offset18 = one_pixel * 35.49246764269043;
  float offset19 = one_pixel * 37.492043284532144;
  float offset20 = one_pixel * 39.49161892637386;
  float offset21 = one_pixel * 41.491194568215576;
  float offset22 = one_pixel * 43.490770210057285;
  float offset23 = one_pixel * 45.490345851899;
  float offset24 = one_pixel * 47.48992149374072;
  float offset25 = one_pixel * 49.48949713558243;
  float offset26 = one_pixel * 51.48907277742415;
  float offset27 = one_pixel * 53.48864841926586;
  float offset28 = one_pixel * 55.48822406110757;
  float offset29 = one_pixel * 57.48779970294929;
  float offset30 = one_pixel * 59.487375344791005;
  float offset31 = one_pixel * 61.48695098663272;
  float offset32 = one_pixel * 63.48652662847443;
  float offset33 = one_pixel * 65.48610227031615;
  float offset34 = one_pixel * 67.48567791215787;
  float offset35 = one_pixel * 69.48525355399957;
  float offset36 = one_pixel * 71.48482919584129;
  float offset37 = one_pixel * 73.484404837683;
  float offset38 = one_pixel * 75.48398047952472;
  float offset39 = one_pixel * 77.48355612136643;
  float offset40 = one_pixel * 79.48313176320815;
  float offset41 = one_pixel * 81.48270740504987;
  float offset42 = one_pixel * 83.48228304689158;

  f_color = (
    0.0012228700972014535 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset42, coords.y)) +
    0.001406727866404052 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset41, coords.y)) +
    0.0016127387934939353 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset40, coords.y)) +
    0.0018426473943326184 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset39, coords.y)) +
    0.002098189879542869 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset38, coords.y)) +
    0.0023810678210118216 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset37, coords.y)) +
    0.0026929187500694864 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset36, coords.y)) +
    0.0030352838999052555 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset35, coords.y)) +
    0.0034095734058253698 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset34, coords.y)) +
    0.0038170293825375633 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset33, coords.y)) +
    0.004258687404961335 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset32, coords.y)) +
    0.00473533702486083 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset31, coords.y)) +
    0.005247482056283134 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset30, coords.y)) +
    0.005795301454499993 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset29, coords.y)) +
    0.006378611691898849 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset28, coords.y)) +
    0.006996831596054691 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset27, coords.y)) +
    0.007648950656200809 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset26, coords.y)) +
    0.008333501820992904 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset25, coords.y)) +
    0.009048539799812799 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset24, coords.y)) +
    0.009791625839535774 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset23, coords.y)) +
    0.010559819877161583 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset22, coords.y)) +
    0.011349680865414115 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset21, coords.y)) +
    0.012157275933847354 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset20, coords.y)) +
    0.012978198883795665 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset19, coords.y)) +
    0.013807598324488872 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset18, coords.y)) +
    0.014640215543789926 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset17, coords.y)) +
    0.015470431975372971 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset16, coords.y)) +
    0.0162923258807897 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset15, coords.y)) +
    0.017099737616634258 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset14, coords.y)) +
    0.017886342611380408 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset13, coords.y)) +
    0.018645730941255573 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset12, coords.y)) +
    0.01937149217764173 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset11, coords.y)) +
    0.020057303987643854 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset10, coords.y)) +
    0.02069702281181379 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset9, coords.y)) +
    0.02128477482491568 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset8, coords.y)) +
    0.02181504531233062 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset7, coords.y)) +
    0.022282764570147735 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset6, coords.y)) +
    0.022683388463568696 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset5, coords.y)) +
    0.023012971856678357 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset4, coords.y)) +
    0.02326823325586946 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset3, coords.y)) +
    0.023446609186457693 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset2, coords.y)) +
    0.023546297042792 * texture(sampler2D(t_input, s_input), vec2(coords.x - offset1, coords.y)) +
    0.011785642841568838 * texture(sampler2D(t_input, s_input), coords) +
    0.023546297042792 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset1, coords.y)) +
    0.023446609186457693 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset2, coords.y)) +
    0.02326823325586946 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset3, coords.y)) +
    0.023012971856678357 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset4, coords.y)) +
    0.022683388463568696 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset5, coords.y)) +
    0.022282764570147735 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset6, coords.y)) +
    0.02181504531233062 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset7, coords.y)) +
    0.02128477482491568 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset8, coords.y)) +
    0.02069702281181379 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset9, coords.y)) +
    0.020057303987643854 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset10, coords.y)) +
    0.01937149217764173 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset11, coords.y)) +
    0.018645730941255573 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset12, coords.y)) +
    0.017886342611380408 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset13, coords.y)) +
    0.017099737616634258 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset14, coords.y)) +
    0.0162923258807897 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset15, coords.y)) +
    0.015470431975372971 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset16, coords.y)) +
    0.014640215543789926 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset17, coords.y)) +
    0.013807598324488872 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset18, coords.y)) +
    0.012978198883795665 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset19, coords.y)) +
    0.012157275933847354 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset20, coords.y)) +
    0.011349680865414115 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset21, coords.y)) +
    0.010559819877161583 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset22, coords.y)) +
    0.009791625839535774 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset23, coords.y)) +
    0.009048539799812799 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset24, coords.y)) +
    0.008333501820992904 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset25, coords.y)) +
    0.007648950656200809 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset26, coords.y)) +
    0.006996831596054691 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset27, coords.y)) +
    0.006378611691898849 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset28, coords.y)) +
    0.005795301454499993 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset29, coords.y)) +
    0.005247482056283134 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset30, coords.y)) +
    0.00473533702486083 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset31, coords.y)) +
    0.004258687404961335 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset32, coords.y)) +
    0.0038170293825375633 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset33, coords.y)) +
    0.0034095734058253698 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset34, coords.y)) +
    0.0030352838999052555 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset35, coords.y)) +
    0.0026929187500694864 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset36, coords.y)) +
    0.0023810678210118216 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset37, coords.y)) +
    0.002098189879542869 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset38, coords.y)) +
    0.0018426473943326184 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset39, coords.y)) +
    0.0016127387934939353 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset40, coords.y)) +
    0.001406727866404052 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset41, coords.y)) +
    0.0012228700972014535 * texture(sampler2D(t_input, s_input), vec2(coords.x + offset42, coords.y))
  );
}
